//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeforeBuying.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeforeBuyingContainer : DbContext
    {
        public BeforeBuyingContainer()
            : base("name=BeforeBuyingContainer")
        {
        }

        public BeforeBuyingContainer(string connString)
            : base("name=BeforeBuyingContainer")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> ItemSet { get; set; }
        public virtual DbSet<Shop> ShopSet { get; set; }
        public virtual DbSet<Price> PriceSet { get; set; }
        public virtual DbSet<Discount> DiscountSet { get; set; }
    }
}
