//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeforeBuying.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int Id { get; set; }
        public System.DateTime DiscountFrom { get; set; }
        public System.DateTime DiscountTo { get; set; }
        public short Percent { get; set; }
        public decimal PriceInclVAT { get; set; }
        public Nullable<int> PriceId { get; set; }
    
        public virtual Price Price { get; set; }
    }
}
